/**************************************************************************
* Filename:
* ---------
*  ResID\ResID.h : header file
*
* Description:
* ------------
*	
*
* This is auto generated by ResEditor.exe
**************************************************************************/

#if !defined _RESID_RESID_H_
#define _RESID_RESID_H_


#ifdef __cplusplus
    extern "C" {
#endif

#define  STR_ID_HELLO    1


#ifdef __cplusplus
    }
#endif

#endif  /* _RESID_RESID_H_ */

